times = ('Botafogo', 'Palmeiras', 'Fluminense', 'Atlético-MG', 'Cruzeiro', 'Atlético-PR', 'São Paulo', 'Santos', 'Fortaleza', 'Bragantino', 'Flamengo')
print(f'Lista de times do Brasileirão: {times}')
print(f'Os 5 primeiros são: {times[0:5]}')
print(f'Os 4 últimos são: {times[-4:]}')
print(f'Times em ordem alfabética: {sorted(times)}')